### ISSUE TITLE
Crash when uploading

### ISSUE THREAD

**Issue by wenduof** [HMS-Core/hms-3d-modeling-demo#1] opened 2021-08-03 06:42 UTC
![Screenshot_2021-08-03-14-25-41-358_com miui bugreport](https://user-images.githubusercontent.com/19146532/127968887-1ab36cbd-df9a-4b3d-8313-d70925da26e2.png)
After data collection, the app will try to upload data and then it will get a crash.
If I restart the app and try to upload data manually, the crash happens too. The log is attached. 

Phone: MI 9
OS: MIUI 10 9.2.28
Android: 9
Kernel: 4.14.83

**Comment by caibobit** [comment] 2021-08-03 07:15
The cause is that the AGC does not set the data processing location. This problem will be fixed in the next version.

**Comment by wenduof** [comment] 2021-08-03 07:51
> The cause is that the AGC does not set the data processing location. This problem will be fixed in the next version.

When will  the next version be released?

**Comment by tygm** [comment] 2021-08-06 09:28
华为p30，一样的错误，为什么自家的设备都不行呢
![image](https://user-images.githubusercontent.com/12265817/128489550-0b1fefa7-7cb5-4f29-80c5-00b019de9773.png)

**Comment by caibobitHuawei** [comment] 2021-08-13 01:46
> The cause is that the AGC does not set the data processing location. This problem will be fixed in the next version.

The next version will be released in late August. The modeling effect and experience will be improved.

**Comment by SneakerMa** [comment] 2021-08-13 01:46
Please setting the data processing location on AGC.

**Comment by caibobitHuawei** [comment] 2021-08-24 09:37
This problem has been resolved in the latest version 1.1.0.300. If the data processing location is not set, an error code will be displayed to notify developers. The sample code has been updated so you can try it.

**Closed by caibobitHuawei** 2021-08-24 09:37 UTC
